services:
  - type: web
    name: taskflow-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://taskflow-nu-two.vercel.app
      - key: DATABASE_URL
        fromDatabase:
          name: taskflow-db
          property: connectionString

databases:
  - name: taskflow-db
    databaseName: taskflow
    user: taskflow
